#!/bin/bash

MASTER_IP="129.104.253.36"
PORT="29502"
NNODES=10
NPROC_PER_NODE=1

ssh dindon.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py"&
ssh malleole.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=1 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
ssh kamiche.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=2 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
ssh loriol.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=3 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
ssh quetzal.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=4 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
ssh jabiru.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=5 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
ssh epervier.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=6 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
# ssh linotte.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=7 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} /Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /dev/null 2>&1&
ssh harpie.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=7 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
ssh faisan.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=8 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
ssh traquet.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=9 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} ~/Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /users/eleves-b/2022/mathias.perez/Desktop/JuridixAssistant/log.txt 2>&1&
# ssh verdier.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=11 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} /Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /dev/null 2>&1&
# ssh nandou.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=12 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} /Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /dev/null 2>&1&
# ssh rouloul.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=13 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} /Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /dev/null 2>&1&
# ssh gelinotte.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=14 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} /Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /dev/null 2>&1&
# ssh perdrix.polytechnique.fr "python -m torch.distributed.run --nproc_per_node=${NPROC_PER_NODE} --nnodes=${NNODES} --node_rank=15 --rdzv_backend=c10d --rdzv_endpoint=${MASTER_IP}:${PORT} /Desktop/JuridixAssistant/fine_tuning_bloom.py.py" > /dev/null 2>&1&